import { Stack, Image, Box, Text } from "@chakra-ui/react";

export function AboutMe() {
  return (
    <Stack
      direction="row"
      justify="flex-start"
      align="center"
      width="100vw"
      spacing="10px"
      height="1500px"
      background="#F0EEED"
    >
      <Stack
        width="100vw"
        height="100vh"
        direction="row"
        justify="flex-start"
        align="center"
        spacing="10%"
      >
        <Stack
          width="55%"
          justify="flex-start"
          align="flex-start"
          spacing="40px"
          direction="column"
          paddingLeft="5%"
        >
          <Box>
            <Image
              alt="Crypto-wallet"
              src="https://images.unsplash.com/photo-1614787913553-8aa43d6fc7f5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1771&q=80"
              width="100%"
              height="226px"
              maxWidth="100%"
              objectFit="cover"
              paddingLeft="35%"
              margin="2%"
            />
            <Image
              alt="Crypto-wallet"
              src="https://images.unsplash.com/photo-1614787913553-8aa43d6fc7f5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1771&q=80"
              width="100%"
              height="223px"
              maxWidth="100%"
              objectFit="cover"
              paddingLeft="25%"
              margin="2%"
            />
            <Image
              alt="Crypto-wallet"
              src="https://images.unsplash.com/photo-1614787913553-8aa43d6fc7f5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1771&q=80"
              width="100%"
              height="223px"
              maxWidth="100%"
              objectFit="cover"
              paddingLeft="15%"
              margin="2%"
            />
          </Box>
        </Stack>
        <Stack
          justify="flex-start"
          align="flex-start"
          spacing="40px"
          width="45%"
          height="50%"
          maxWidth="100%"
          paddingLeft="10vw"
        >
          <Box>
            <Text
              fontFamily="Poppins"
              lineHeight="0.75"
              fontWeight="medium"
              fontSize="9rem"
              color="black"
              width="100%"
              height="50%"
              maxWidth="100%"
            >
              About Me
            </Text>
          </Box>
          <Text
            fontFamily="Poppins"
            lineHeight="1.5"
            fontWeight="medium"
            fontSize="2rem"
            color="#000000"
            width="504px"
            height="101px"
            maxWidth="100%"
          >
            Front-end developer based in Thailand. I am coding with a clean and
            beautiful problem solving in mind.
          </Text>
        </Stack>
      </Stack>
    </Stack>
  );
}
